### ISSUE TITLE
SIGSEGV ...

### ISSUE THREAD

**Issue by prologic** [khlieng/dispatch#13]
Not sure what this stack trace is (_yet_):

```
prologic@Jamess-MacBook
Thu May 17 17:35:34
~/go/src/github.com/khlieng/dispatch
 (master) 0
$ ./dispatch

    ____   _                     _         _
   |  _ \ (_) ___  _ __    __ _ | |_  ___ | |__
   | | | || |/ __|| '_ \  / _  || __|/ __|| '_ \
   | |_| || |\__ \| |_) || (_| || |_| (__ | | | |
   |____/ |_||___/| .__/  \__,_| \__|\___||_| |_|
                  |_|
                       v0.4

2018/05/17 17:35:39 Storing data at /Users/prologic/.dispatch
2018/05/17 17:35:39 [HTTP] Listening on port 8000
2018/05/17 17:35:42 [::1]:53076 [Auth] Create session | User ID: 2
2018/05/17 17:35:46 [::1]:53082 [Auth] GET /ws/connect | Valid token | User ID: 2
2018/05/17 17:35:46 [::1]:53082 [Session] User ID: 2 | 0 IRC connections | 1 WebSocket connections
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x14bf41e]

goroutine 25 [running]:
github.com/khlieng/dispatch/vendor/github.com/blevesearch/bleve.(*indexImpl).Close(0x0, 0x0, 0x0)
	/Users/prologic/go/src/github.com/khlieng/dispatch/vendor/github.com/blevesearch/bleve/index_impl.go:743 +0x2e
github.com/khlieng/dispatch/storage.(*User).closeMessageLog(0xc4200b68a0)
	/Users/prologic/go/src/github.com/khlieng/dispatch/storage/user_messages.go:190 +0x46
github.com/khlieng/dispatch/storage.(*User).Remove(0xc4200b68a0)
	/Users/prologic/go/src/github.com/khlieng/dispatch/storage/user.go:230 +0x7e
github.com/khlieng/dispatch/server.(*Session).run(0xc4200b6a20)
	/Users/prologic/go/src/github.com/khlieng/dispatch/server/session.go:212 +0x1fb
created by github.com/khlieng/dispatch/server.reconnectIRC
	/Users/prologic/go/src/github.com/khlieng/dispatch/server/irc.go:37 +0x135
```

**Comment by prologic** [comment]
What are you using bleeve for?

**Comment by khlieng** [comment]
Message search

**Comment by prologic** [comment]
Gotcha; this exhibits the following behavior (*before finally crashing*):

* Click "Connect"
* Wait... Wait... Wait...
* Eventually you SEGV
